---
- hosts: linux
  gather_facts: True
  become: yes
  
  vars:
    source_file: ./index.j2
    dest_file: /var/www/html
   

  tasks:
    - name: Install Apache Web Server for RPM
      yum: name=httpd state=latest
      when: ansible_os_family == "RedHat"

    
    - name: Print Linux Family
      debug: var=ansible_os_family
      
    - name:     Generate index.html from jinja2 template and copy to the remote host
      template: src={{ source_file }} dest={{ dest_file }}/index.html mode=0555
      notify:   Restart Httpd
      when:     ansible_os_family == "RedHat"
      

      
    - name: Start Apache Web Server
      service: name=httpd state=started enabled=yes
      when: ansible_os_family == "RedHat"

    
  handlers:
  - name: Restart Httpd
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"

    
    
